<!DOCTYPE html>
<html lang="en"><head>
<script src="10a-hlm-pred_files/libs/clipboard/clipboard.min.js"></script>
<script src="10a-hlm-pred_files/libs/quarto-html/tabby.min.js"></script>
<script src="10a-hlm-pred_files/libs/quarto-html/popper.min.js"></script>
<script src="10a-hlm-pred_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="10a-hlm-pred_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10a-hlm-pred_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="10a-hlm-pred_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Dr.&nbsp;Mine Dogucu">
  <title>(Normal) Hierarchical Models with Predictors</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="10a-hlm-pred_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="10a-hlm-pred_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="10a-hlm-pred_files/libs/revealjs/dist/theme/quarto-d0e4eec2d26d0539cf9d21248d71fa40.css">
  <link href="10a-hlm-pred_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="10a-hlm-pred_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="10a-hlm-pred_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="10a-hlm-pred_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="https://stats115.com/img/logo.png" data-background-position="50% 85%" data-background-size="5%" class="quarto-title-block center">
  <h1 class="title">(Normal) Hierarchical Models with Predictors</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Mine Dogucu 
</div>
</div>
</div>

</section>
<section id="section" class="slide level2">
<h2></h2>
<p>The notes for this lecture are derived from <a href="https://www.bayesrulesbook.com/chapter-17">Chapter 17 of the Bayes Rules! book</a></p>
</section>
<section id="section-1" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">data</span>(cherry_blossom_sample)</span>
<span id="cb1-2"><a href=""></a>running <span class="ot">&lt;-</span> cherry_blossom_sample</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># Remove NAs</span></span>
<span id="cb2-2"><a href=""></a>running <span class="ot">&lt;-</span> running <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href=""></a>  <span class="fu">select</span>(runner, age, net) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href=""></a>  <span class="fu">na.omit</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="complete-pooling" class="slide level2">
<h2>Complete pooling</h2>

<img data-src="img/complete_pool_diagram.png" style="width:70.0%" class="r-stretch"></section>
<section id="complete-pooling-1" class="slide level2">
<h2>Complete pooling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>complete_pooled_model <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(</span>
<span id="cb3-2"><a href=""></a>  net <span class="sc">~</span> age, </span>
<span id="cb3-3"><a href=""></a>  <span class="at">data =</span> running, <span class="at">family =</span> gaussian, </span>
<span id="cb3-4"><a href=""></a>  <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">2.5</span>, <span class="at">autoscale =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-5"><a href=""></a>  <span class="at">prior =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">2.5</span>, <span class="at">autoscale =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-6"><a href=""></a>  <span class="at">prior_aux =</span> <span class="fu">exponential</span>(<span class="dv">1</span>, <span class="at">autoscale =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-7"><a href=""></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">84735</span>, <span class="at">refresh=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
<p><span class="math display">\[\begin{equation}
\begin{split}
Y_{ij} | \beta_0, \beta_1, \sigma &amp; \sim N(\mu_i, \sigma^2) \;\; \text{ where } \mu_i = \beta_0 + \beta_1 X_{ij} \\
\beta_{0c} &amp; \sim N(0, 35^2) \\
\beta_1 &amp; \sim N(0, 15^2) \\
\sigma  &amp; \sim \text{Exp}(0.072) \\
\end{split}
\end{equation}\]</span></p>
<p>This model depends upon three <strong>global parameters</strong>: intercept <span class="math inline">\(\beta_0\)</span>, age coefficient <span class="math inline">\(\beta_1\)</span>, and variability from the regression model <span class="math inline">\(\sigma\)</span>.</p>
</section>
<section id="section-3" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="co"># Posterior summary statistics</span></span>
<span id="cb4-2"><a href=""></a>model_summary <span class="ot">&lt;-</span> <span class="fu">tidy</span>(complete_pooled_model, </span>
<span id="cb4-3"><a href=""></a>                      <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.80</span>)</span>
<span id="cb4-4"><a href=""></a>model_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   75.2      24.6     43.7     106.   
2 age            0.268     0.446   -0.302     0.842</code></pre>
</div>
</div>
<p>The <code>net</code> running times versus <code>age</code> exhibit a weak relationship with a posterior median model of 75.2 <span class="math inline">\(+\)</span> 0.268 age.</p>
</section>
<section id="section-4" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section>
<section id="hierarchical-model-with-varying-intercepts" class="slide level2">
<h2>Hierarchical model with varying intercepts</h2>
<p>Layer 1:</p>
<p><span class="math inline">\(Y_{ij} | \mu_j, \sigma_y   \hspace{-0.075in} \sim \text{model of how song popularity varies WITHIN artist } j\)</span></p>
<div class="fragment">
<p>Layer 2:</p>
<p><span class="math inline">\(\mu_j | \mu, \sigma_\mu  \hspace{-0.075in} \sim \text{model of how the typical popularity} \mu_j \text{varies BETWEEN artists}\)</span></p>
</div>
<div class="fragment">
<p>Layer 3:</p>
<p><span class="math inline">\(\mu, \sigma_y, \sigma_\mu   \hspace{-0.075in} \sim \text{prior models for shared global parameters}\)</span></p>
</div>
</section>
<section id="layer-1-variability-within-runner" class="slide level2">
<h2>Layer 1: Variability within runner</h2>
<p>The first layer of the simple Normal hierarchical model assumes that each runner’s net running times <span class="math inline">\(Y_{ij}\)</span> vary normally around their own mean time <span class="math inline">\(\mu_j\)</span>, with no consideration of their age <span class="math inline">\(X_{ij}\)</span>:</p>
<p><span class="math display">\[Y_{ij} | \mu_{j}, \sigma_y \sim N(\mu_{j}, \sigma_y^2)\]</span></p>
</section>
<section id="section-5" class="slide level2">
<h2></h2>
<p>To incorporate information about age into our understanding of running times within runners, we can replace the <span class="math inline">\(\mu_{j}\)</span> with runner-specific means <span class="math inline">\(\mu_{ij}\)</span>, which depend upon the runner’s age in their <span class="math inline">\(i\)</span>th race, <span class="math inline">\(X_{ij}\)</span>.</p>
<p><span class="math display">\[\mu_{ij} = \beta_{0j} + \beta_1 X_{ij}\]</span></p>
</section>
<section id="section-6" class="slide level2">
<h2></h2>
<p>Thus, the first layer of our hierarchical model describes the relationship between net times and age <strong>within</strong> each runner <span class="math inline">\(j\)</span> by:</p>
<p><span class="math display">\[\begin{equation}
Y_{ij} | \beta_{0j}, \beta_1, \sigma_y \sim N(\mu_{ij}, \sigma_y^2) \;\; \text{ where } \; \mu_{ij} = \beta_{0j} + \beta_1 X_{ij}
\end{equation}\]</span></p>
</section>
<section id="section-7" class="slide level2">
<h2></h2>
<p>Note that <span class="math inline">\(\beta_{0j}\)</span> depends upon <span class="math inline">\(j\)</span>, and thus is runner- or <strong>group-specific</strong>:</p>
<ul>
<li class="fragment"><span class="math inline">\(\beta_{0j}\)</span> = intercept of the regression model for runner <span class="math inline">\(j\)</span>.</li>
</ul>
<div class="fragment">
<p>The other parameters are <strong>global</strong>, or shared across all runners <span class="math inline">\(j\)</span></p>
<ul>
<li class="fragment"><span class="math inline">\(\beta_1\)</span> = global age coefficient, i.e., the typical change in a runner’s net time per one year increase in age; and</li>
<li class="fragment"><span class="math inline">\(\sigma_y\)</span> = <strong>within-group variability</strong> around the mean regression model <span class="math inline">\(\beta_{0j} + \beta_1 X_{ij}\)</span>, and hence a measure of the <em>strength</em> of the relationship between an individual runner’s time and their age.</li>
</ul>
</div>
</section>
<section id="section-8" class="slide level2">
<h2></h2>
<p>The first layer of our hierarchical model assumes that relationships between running time and age <em>randomly</em> vary from runner to runner, having <em>different</em> intercepts <span class="math inline">\(\beta_{0j}\)</span> but a shared age coefficient <span class="math inline">\(\beta_1\)</span>.</p>
</section>
<section id="section-9" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="layer-2-variability-between-runners" class="slide level2">
<h2>Layer 2: Variability between runners</h2>
<p>In this layer we capture how the relationships between running time and age vary from runner to runner, i.e., <strong>between</strong> runners.</p>
<div class="fragment">
<p>In this layer will model variability in the intercept parameters <span class="math inline">\(\beta_{0j}\)</span>.</p>
</div>
<div class="fragment">
<p><span class="math display">\[\begin{equation}
\beta_{0j} | \beta_0, \sigma_0 \stackrel{ind}{\sim} N(\beta_0, \sigma_0^2)
\end{equation}\]</span></p>
</div>
</section>
<section id="section-10" class="slide level2">
<h2></h2>
<p>This layer of the hierarchical model which depends upon two new parameters:</p>
<ul>
<li class="fragment"><span class="math inline">\(\beta_0\)</span> = the <strong>global average intercept</strong> across all runners, i.e., the <em>average</em> runner’s baseline speed;</li>
<li class="fragment"><span class="math inline">\(\sigma_0\)</span> = <strong>between-group variability</strong> in intercepts <span class="math inline">\(\beta_{0j}\)</span>, i.e., the extent to which baseline speeds vary from runner to runner.</li>
</ul>
</section>
<section id="layer-3-global-priors" class="slide level2">
<h2>Layer 3: Global priors</h2>
<p>Regression model within runner <span class="math inline">\(j\)</span>: <span class="math inline">\(Y_{ij} | \beta_{0j}, \beta_1, \sigma_y  \sim N(\mu_{ij}, \sigma_y^2)  \text{ with }   \mu_{ij} = \beta_{0j} + \beta_1 X_{ij}\)</span></p>
<p>variability in baseline speeds BETWEEN runners: <span class="math inline">\(\beta_{0j} | \beta_0, \sigma_0   \stackrel{ind}{\sim} N(\beta_0, \sigma_0^2)\)</span></p>
</section>
<section id="section-11" class="slide level2">
<h2></h2>
<p>priors on global parameters:</p>
<p><span class="math display">\[\beta_{0c}   \sim N(m_0, s_0^2)  \]</span></p>
<p><span class="math display">\[\beta_1   \sim N(m_1, s_1^2)\]</span> <span class="math display">\[\sigma_y  \sim \text{Exp}(l_y)\]</span> <span class="math display">\[\sigma_0  \sim \text{Exp}(l_0)\]</span></p>
</section>
<section id="normal-hierarchical-regression-assumptions" class="slide level2">
<h2>Normal hierarchical regression assumptions</h2>
<p>Let <span class="math inline">\(Y_{ij}\)</span> and <span class="math inline">\(X_{ij}\)</span> denote observations for the <span class="math inline">\(i\)</span>th observation in group <span class="math inline">\(j\)</span>. The appropriateness of the Bayesian Normal hierarchical regression model of <span class="math inline">\(Y_{ij}\)</span> by <span class="math inline">\(X_{ij}\)</span> depends upon the following assumptions.</p>
<ul>
<li class="fragment"><strong>Structure of the data</strong><br>
Conditioned on predictor <span class="math inline">\(X_{ij}\)</span>, the outcomes <span class="math inline">\(Y_{ij}\)</span> on any one group <span class="math inline">\(j\)</span> are <em>independent</em> of those on another group <span class="math inline">\(k\)</span>, <span class="math inline">\(Y_{ik}\)</span>. However, different data points <em>within</em> the same group <span class="math inline">\(j\)</span>, <span class="math inline">\(Y_{ij}\)</span> and <span class="math inline">\(Y_{hj}\)</span>, are <em>correlated</em>.</li>
</ul>
</section>
<section id="section-12" class="slide level2">
<h2></h2>
<ul>
<li class="fragment"><strong>Structure of the relationship</strong><br>
Within any group <span class="math inline">\(j\)</span>, the typical outcome of <span class="math inline">\(Y_{ij}\)</span> ( <span class="math inline">\(\mu_{ij}\)</span> ) can be written as a <strong>linear function</strong> of predictor <span class="math inline">\(X_{ij}\)</span>.</li>
</ul>
<div class="fragment">
<ul>
<li class="fragment"><strong>Structure of the variability within groups</strong><br>
Within any group <span class="math inline">\(j\)</span> and at any predictor value <span class="math inline">\(X_{ij}\)</span>, the observed values of <span class="math inline">\(Y_{ij}\)</span> will vary <strong>normally</strong> around mean <span class="math inline">\(\mu_{ij}\)</span> with consistent standard deviation <span class="math inline">\(\sigma_y\)</span>. . . .</li>
<li class="fragment"><strong>Structure of the variability between groups</strong><br>
The group-specific baselines or intercepts, <span class="math inline">\(\beta_{0j}\)</span>, vary <strong>normally</strong> around a global intercept <span class="math inline">\(\beta_0\)</span> with standard deviation <span class="math inline">\(\sigma_0\)</span>.</li>
</ul>
</div>
</section>
<section id="section-13" class="slide level2">
<h2></h2>
<p><strong>Connecting the hierarchical and complete pooled models</strong></p>
<p>The complete pooled model is a <em>special case</em> of the random intercepts model. These two models are equivalent when <span class="math inline">\(\sigma_0 = 0\)</span>, i.e., when the intercepts do <em>not</em> differ from group to group.</p>
</section>
<section id="another-way-to-think-about-it" class="slide level2">
<h2>Another way to think about it</h2>
<p><em>Equivalently</em>, we can think of the runner-specific intercepts as random <em>tweaks</em> or <em>adjustments</em> <span class="math inline">\(b_{0j}\)</span> to <span class="math inline">\(\beta_0\)</span>,</p>
<p><span class="math display">\[\beta_{0j} = \beta_0 + b_{0j}\]</span></p>
<p>where these tweaks are normal deviations from <em>0</em> with standard deviation <span class="math inline">\(\sigma_0\)</span>:</p>
<p><span class="math display">\[b_{0j} \sim N(0, \sigma_0^2)\]</span></p>
</section>
<section id="section-14" class="slide level2">
<h2></h2>
<p>Suppose that some runner <span class="math inline">\(j\)</span> has a baseline running speed of <span class="math inline">\(\beta_{0j} = 24\)</span> minutes, whereas the average baseline speed across <em>all</em> runners is <span class="math inline">\(\beta_0 = 19\)</span> minutes. Thus, at any age, runner <span class="math inline">\(j\)</span> tends to run 5 minutes slower than average. That is, <span class="math inline">\(b_{0j} = 5\)</span> and</p>
<p><span class="math display">\[\beta_{0j} = \beta_0 + b_{0j} = 19 + 5 = 24\]</span></p>
</section>
<section id="section-15" class="slide level2">
<h2></h2>
<p>In general, then, we can reframe Layers 1 and 2 of our hierarchical model as follows:</p>
<p><span class="math display">\[\begin{equation}
\begin{split}
Y_{ij} | \beta_{0j}, \beta_1, \sigma_y &amp; \sim N(\mu_{ij}, \sigma_y^2) \;\; \text{ with } \;\;  \mu_{ij} = (\beta_0 + b_{0j}) + \beta_1 X_{ij}  \\
b_{0j} | \sigma_0  &amp; \stackrel{ind}{\sim} N(0, \sigma_0^2)  \\
\beta_{0c}  &amp; \sim N(m_0, s_0^2) \\
\beta_1  &amp; \sim N(m_1, s_1^2)  \\
\sigma_y &amp; \sim \text{Exp}(l_y)  \\
\sigma_0 &amp; \sim \text{Exp}(l_0).  \\
\end{split}
\end{equation}\]</span></p>
</section>
<section id="section-16" class="slide level2">
<h2></h2>
<p><span class="math display">\[\begin{equation}
\begin{split}
Y_{ij} | \beta_{0j}, \beta_1, \sigma_y &amp; \sim N(\mu_{ij}, \sigma_y^2) \;\; \text{ with } \;\;  \mu_{ij} = \beta_{0j} + \beta_1 X_{ij} \\
\beta_{0j} | \beta_0, \sigma_0  &amp; \stackrel{ind}{\sim} N(\beta_0, \sigma_0^2) \\
\beta_{0c}  &amp; \sim N(100, 10^2) \\
\beta_1  &amp; \sim N(2.5, 1^2) \\
\sigma_y &amp; \sim \text{Exp}(0.072) \\
\sigma_0 &amp; \sim \text{Exp}(1) \\
\end{split}
\end{equation}\]</span></p>
</section>
<section id="section-17" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>running_model_1_prior <span class="ot">&lt;-</span> <span class="fu">stan_glmer</span>(</span>
<span id="cb6-2"><a href=""></a>  net <span class="sc">~</span> age <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> runner), </span>
<span id="cb6-3"><a href=""></a>  <span class="at">data =</span> running, <span class="at">family =</span> gaussian,</span>
<span id="cb6-4"><a href=""></a>  <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">100</span>, <span class="dv">10</span>),</span>
<span id="cb6-5"><a href=""></a>  <span class="at">prior =</span> <span class="fu">normal</span>(<span class="fl">2.5</span>, <span class="dv">1</span>), </span>
<span id="cb6-6"><a href=""></a>  <span class="at">prior_aux =</span> <span class="fu">exponential</span>(<span class="dv">1</span>, <span class="at">autoscale =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-7"><a href=""></a>  <span class="at">prior_covariance =</span> <span class="fu">decov</span>(<span class="at">reg =</span> <span class="dv">1</span>, <span class="at">conc =</span> <span class="dv">1</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">scale =</span> <span class="dv">1</span>),</span>
<span id="cb6-8"><a href=""></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">84735</span>, </span>
<span id="cb6-9"><a href=""></a>  <span class="at">prior_PD =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li class="fragment">We specify the model of <code>net</code> times by <code>age</code> by the formula <code>net ~ age + (1 | runner)</code>. This essentially combines a non-hierarchical regression formula (<code>net ~ age</code>) with that for a hierarchical model with no predictor (<code>net ~ (1 | runner)</code>).</li>
<li class="fragment">We specify <code>prior_PD = TRUE</code> to indicate that we wish to simulate parameters from the prior, not posterior, models.</li>
</ul>
</section>
<section id="section-18" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb7-2"><a href=""></a>running <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href=""></a>  <span class="fu">add_fitted_draws</span>(running_model_1_prior, <span class="at">n =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href=""></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span></span>
<span id="cb7-5"><a href=""></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .value, <span class="at">group =</span> <span class="fu">paste</span>(runner, .draw))) <span class="sc">+</span> </span>
<span id="cb7-6"><a href=""></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> .draw)</span>
<span id="cb7-7"><a href=""></a></span>
<span id="cb7-8"><a href=""></a>running <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href=""></a>  <span class="fu">add_predicted_draws</span>(running_model_1_prior, <span class="at">n =</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-10"><a href=""></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> net)) <span class="sc">+</span></span>
<span id="cb7-11"><a href=""></a>    <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> .prediction, <span class="at">group =</span> .draw)) <span class="sc">+</span></span>
<span id="cb7-12"><a href=""></a>    <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">100</span>,<span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-19" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/prior_mean-1.png" width="960" class="r-stretch"></section>
<section id="posterior-simulation-analysis" class="slide level2">
<h2>Posterior simulation &amp; analysis</h2>
<p>Most runners’ times <em>do</em> tend to increase with age, and there is variability between the runners themselves – some tend to be faster than others.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">ggplot</span>(running, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span> </span>
<span id="cb8-2"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-3"><a href=""></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> runner)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-20" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"></section>
<section id="section-21" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="co"># Simulate the posterior</span></span>
<span id="cb9-2"><a href=""></a>running_model_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(running_model_1_prior, <span class="at">prior_PD =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href=""></a></span>
<span id="cb9-4"><a href=""></a><span class="co"># Check the prior specifications</span></span>
<span id="cb9-5"><a href=""></a><span class="fu">prior_summary</span>(running_model_1)</span>
<span id="cb9-6"><a href=""></a></span>
<span id="cb9-7"><a href=""></a><span class="co"># Markov chain diagnostics</span></span>
<span id="cb9-8"><a href=""></a><span class="fu">mcmc_trace</span>(running_model_1)</span>
<span id="cb9-9"><a href=""></a><span class="fu">mcmc_dens_overlay</span>(running_model_1)</span>
<span id="cb9-10"><a href=""></a><span class="fu">mcmc_acf</span>(running_model_1)</span>
<span id="cb9-11"><a href=""></a><span class="fu">neff_ratio</span>(running_model_1)</span>
<span id="cb9-12"><a href=""></a><span class="fu">rhat</span>(running_model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-22" class="slide level2">
<h2></h2>
<p>There are a whopping 40 parameters in our model: 36 runner-specific intercept parameters ( <span class="math inline">\(\beta_{0j}\)</span> ) in addition to 4 global parameters ( <span class="math inline">\(\beta_0, \beta_1, \sigma_y, \sigma_0\)</span> ). These are labeled as follows in the <code>stan_glmer()</code> simulation results:</p>
<ul>
<li class="fragment"><code>(Intercept)</code> = <span class="math inline">\(\beta_0\)</span></li>
<li class="fragment"><code>age</code> = <span class="math inline">\(\beta_1\)</span></li>
<li class="fragment"><code>b[(Intercept) runner:j]</code> = <span class="math inline">\(b_{0j} = \beta_{0j} - \beta_0\)</span>, the <em>difference</em> between runner <span class="math inline">\(j\)</span>’s baseline speed and the average baseline speed</li>
<li class="fragment"><code>sigma</code> = <span class="math inline">\(\sigma_y\)</span></li>
<li class="fragment"><code>Sigma[runner:(Intercept),(Intercept)]</code> = <span class="math inline">\(\sigma_0^2\)</span></li>
</ul>
</section>
<section id="posterior-analysis-of-the-global-relationship" class="slide level2">
<h2>Posterior analysis of the global relationship</h2>
<p>Consider the <strong>global relationship</strong> between running time and age for the <em>typical</em> runner:</p>
<p><span class="math display">\[\beta_0 + \beta_1 X\]</span></p>
<div class="fragment">
<p>Posterior summaries for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, which are <code>fixed</code> across runners, can be shown with.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>tidy_summary_1 <span class="ot">&lt;-</span> <span class="fu">tidy</span>(running_model_1, <span class="at">effects =</span> <span class="st">"fixed"</span>,</span>
<span id="cb10-2"><a href=""></a>                       <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.80</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="section-23" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>tidy_summary_1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    19.4     12.0       3.91     34.6 
2 age             1.30     0.216     1.03      1.57</code></pre>
</div>
</div>
<p>There’s an 80% chance that the <em>typical</em> runner tends to slow down somewhere between 1.03 and 1.57 minutes per year.</p>
<div class="fragment">
<p>Since this range is entirely and comfortably above 0 we conclude that the <em>typical</em> runner tends to slow down with age.</p>
</div>
</section>
<section id="section-24" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>B0 <span class="ot">&lt;-</span> tidy_summary_1<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb13-2"><a href=""></a>B1 <span class="ot">&lt;-</span> tidy_summary_1<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb13-3"><a href=""></a>running <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href=""></a>  <span class="fu">add_fitted_draws</span>(running_model_1, <span class="at">n =</span> <span class="dv">200</span>, <span class="at">re_formula =</span> <span class="cn">NA</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href=""></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span></span>
<span id="cb13-6"><a href=""></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .value, <span class="at">group =</span> .draw), <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href=""></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> B0, <span class="at">slope =</span> B1, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href=""></a>    <span class="fu">lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">110</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="10a-hlm-pred_files/figure-revealjs/fitted_draw-1.png" width="960" class="r-stretch"></section>
<section id="posterior-analysis-of-group-specific-relationships" class="slide level2">
<h2>Posterior analysis of group-specific relationships</h2>
<p>To examine the <strong>runner-specific relationships</strong> between net running time and age we have</p>
<p><span class="math display">\[\beta_{0j} + \beta_1 X_{ij} \; = (\beta_0 + b_{0j}) + \beta_1 X_{ij}\]</span></p>
</section>
<section id="section-25" class="slide level2">
<h2></h2>
<p>First, the <code>b[(Intercept) runner:j]</code> chains correspond to the <em>difference</em> in the runner-specific and global intercepts <span class="math inline">\(b_{0j}\)</span>. Thus, we obtain MCMC chains for each <span class="math inline">\(\beta_{0j} = \beta_0 + b_{0j}\)</span> by adding the <code>(Intercept)</code> chain to the <code>b[(Intercept) runner:j]</code> chains via <code>spread_draws()</code> and <code>mutate()</code>. We then use <code>median_qi()</code> to obtain posterior summaries of the <span class="math inline">\(\beta_{0j}\)</span> chain for each runner <span class="math inline">\(j\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="co"># Posterior summaries of runner-specific intercepts</span></span>
<span id="cb14-2"><a href=""></a>runner_summaries_1 <span class="ot">&lt;-</span> running_model_1 <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href=""></a>  <span class="fu">spread_draws</span>(<span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, b[,runner]) <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">runner_intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span> <span class="sc">+</span> b) <span class="sc">%&gt;%</span> </span>
<span id="cb14-5"><a href=""></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, <span class="sc">-</span>b) <span class="sc">%&gt;%</span> </span>
<span id="cb14-6"><a href=""></a>  <span class="fu">median_qi</span>(<span class="at">.width =</span> <span class="fl">0.80</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-7"><a href=""></a>  <span class="fu">select</span>(runner, runner_intercept, .lower, .upper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-26" class="slide level2">
<h2></h2>
<p>Consider the results for runners 4 and 5. With a posterior median intercept of 31 minutes vs 6.9 minutes, runner 4 seems to have a slower baseline speed than runner 5. Thus, at any shared age, we would expect runner 4 to run roughly 24.1 minutes slower than runner 5 ( <span class="math inline">\(31 - 6.9\)</span> ):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>runner_summaries_1 <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href=""></a>  <span class="fu">filter</span>(runner <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"runner:4"</span>, <span class="st">"runner:5"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  runner   runner_intercept .lower .upper
  &lt;chr&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 runner:4            31.0   15.5    46.4
2 runner:5             6.89  -8.28   21.9</code></pre>
</div>
</div>
</section>
<section id="section-27" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="co"># 100 posterior plausible models for runners 4 &amp; 5</span></span>
<span id="cb17-2"><a href=""></a>running <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href=""></a>  <span class="fu">filter</span>(runner <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"4"</span>, <span class="st">"5"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href=""></a>  <span class="fu">add_fitted_draws</span>(running_model_1, <span class="at">n =</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href=""></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span></span>
<span id="cb17-6"><a href=""></a>    <span class="fu">geom_line</span>(</span>
<span id="cb17-7"><a href=""></a>      <span class="fu">aes</span>(<span class="at">y =</span> .value, <span class="at">group =</span> <span class="fu">paste</span>(runner, .draw), <span class="at">color =</span> runner),</span>
<span id="cb17-8"><a href=""></a>      <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb17-9"><a href=""></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> runner))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-28" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/posterior_plausible-1.png" width="960" class="r-stretch"></section>
<section id="section-29" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="co"># Plot runner-specific models with the global model</span></span>
<span id="cb18-2"><a href=""></a><span class="fu">ggplot</span>(running, <span class="fu">aes</span>(<span class="at">y =</span> net, <span class="at">x =</span> age, <span class="at">group =</span> runner)) <span class="sc">+</span> </span>
<span id="cb18-3"><a href=""></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> runner_summaries_1, <span class="at">color =</span> <span class="st">"gray"</span>,</span>
<span id="cb18-4"><a href=""></a>              <span class="fu">aes</span>(<span class="at">intercept =</span> runner_intercept, <span class="at">slope =</span> B1)) <span class="sc">+</span> </span>
<span id="cb18-5"><a href=""></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> B0, <span class="at">slope =</span> B1, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb18-6"><a href=""></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">61</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">135</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-30" class="slide level2">
<h2></h2>
<p>The posterior median models for our 36 runners <span class="math inline">\(j\)</span> as calculated from the hierarchical random intercepts model (gray), with the posterior median global model (blue).</p>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-22-1.png" width="960" class="r-stretch"></section>
<section id="posterior-analysis-of-within--and-between-group-variability" class="slide level2">
<h2>Posterior analysis of within- and between-group variability</h2>
<p><span class="math inline">\(\sigma_y\)</span> measures the variability from the mean regression model <strong>within</strong> each runner.</p>
<div class="fragment">
<p><span class="math inline">\(\sigma_0\)</span> measures the variability in baseline running speeds <strong>between</strong> the runners.</p>
</div>
</section>
<section id="section-31" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-23-1.png" width="960" class="r-stretch"><p>Simulated output for the relationship between response variable <span class="math inline">\(Y\)</span> and predictor <span class="math inline">\(X\)</span> when <span class="math inline">\(\sigma_y &lt; \sigma_0\)</span> (a) and <span class="math inline">\(\sigma_y &gt; \sigma_0\)</span> (b).</p>
</section>
<section id="section-32" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a>tidy_sigma <span class="ot">&lt;-</span> <span class="fu">tidy</span>(running_model_1, <span class="at">effects =</span> <span class="st">"ran_pars"</span>)</span>
<span id="cb19-2"><a href=""></a>tidy_sigma</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  term                    group    estimate
  &lt;chr&gt;                   &lt;chr&gt;       &lt;dbl&gt;
1 sd_(Intercept).runner   runner      13.2 
2 sd_Observation.Residual Residual     5.25</code></pre>
</div>
</div>
<div class="fragment">
<p>For a given runner <span class="math inline">\(j\)</span>, we estimate that their observed running time at any age will deviate from <em>their</em> mean regression model by roughly 5.25 minutes ( <span class="math inline">\(\sigma_y\)</span> ).</p>
</div>
<div class="fragment">
<p>In contrast, we expect that baseline speeds vary by roughly 13.2 minutes from runner to runner ( <span class="math inline">\(\sigma_0\)</span> ).</p>
</div>
</section>
<section id="section-33" class="slide level2">
<h2></h2>
<p>Comparatively then, the posterior results suggest that <span class="math inline">\(\sigma_y &lt; \sigma_0\)</span> – there’s greater variability in the models <em>between</em> runners than variability from the model <em>within</em> runners.</p>
<div class="fragment">
<p>Recall:</p>
<p><span class="math display">\[\text{Var}(Y_{ij}) = \sigma_0^2 + \sigma_y^2  .\]</span></p>
</div>
</section>
<section id="section-34" class="slide level2">
<h2></h2>
<p>Thus, <em>proportionally</em> differences between runners account for roughly 86.38% (the majority!) of the total variability in racing times, with fluctuations among individual races within runners explaining the other 13.62%:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a>sigma_0 <span class="ot">&lt;-</span> tidy_sigma[<span class="dv">1</span>,<span class="dv">3</span>]</span>
<span id="cb21-2"><a href=""></a>sigma_y <span class="ot">&lt;-</span> tidy_sigma[<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb21-3"><a href=""></a>sigma_0<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma_0<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> sigma_y<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   estimate
1 0.8637758</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>sigma_y<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma_0<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> sigma_y<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   estimate
1 0.1362242</code></pre>
</div>
</div>
</section>
<section id="hierarchical-model-with-varying-intercepts-slopes" class="slide level2">
<h2>Hierarchical model with varying intercepts &amp; slopes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a><span class="co"># Plot runner-specific models in the data</span></span>
<span id="cb25-2"><a href=""></a>running <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href=""></a>  <span class="fu">filter</span>(runner <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"4"</span>, <span class="st">"5"</span>, <span class="st">"20"</span>, <span class="st">"29"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href=""></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span> </span>
<span id="cb25-5"><a href=""></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb25-6"><a href=""></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb25-7"><a href=""></a>    <span class="fu">facet_grid</span>(<span class="sc">~</span> runner)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-35" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/diff-slopes2-1.png" width="960" class="r-stretch"></section>
<section id="section-36" class="slide level2">
<h2></h2>
<p>Observed trends in running time versus age for the 36 subjects (gray) along with the posterior median model (blue).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">ggplot</span>(running, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net, <span class="at">group =</span> runner)) <span class="sc">+</span> </span>
<span id="cb26-2"><a href=""></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-27-1.png" width="960" class="r-stretch"></section>
<section id="model-building" class="slide level2">
<h2>Model building</h2>
<p>Our goal is to build a model which recognizes that in the relationship between running time and age, <em>both</em> the intercept (i.e., baseline speed) and slope (i.e., rate at which speed changes with age) might vary from runner to runner.</p>
<div class="fragment">
<p><span class="math display">\[\begin{equation}
Y_{ij} | \beta_{0j}, \beta_{1j}, \sigma_y \sim N(\mu_{ij}, \sigma_y^2) \;\; \text{ where } \mu_{ij} = \beta_{0j} + \beta_{1j} X_{ij}  .
\end{equation}\]</span></p>
</div>
</section>
<section id="section-37" class="slide level2">
<h2></h2>
<p>Previously we assumed that the <em>runner-specific</em> intercepts <span class="math inline">\(\beta_{0j}\)</span> are Normally distributed around some <em>global</em> intercept <span class="math inline">\(\beta_0\)</span> with standard deviation <span class="math inline">\(\sigma_0\)</span>, we now also assume that the <em>runner-specific</em> age coefficients <span class="math inline">\(\beta_{1j}\)</span> are Normally distributed around some <em>global</em> age coefficient <span class="math inline">\(\beta_1\)</span> with standard deviation <span class="math inline">\(\sigma_1\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\beta_{0j} | \beta_0, \sigma_0 \sim N(\beta_0, \sigma_0^2)
\;\;\;\; \text{ and } \;\;\;\;
\beta_{1j} | \beta_1, \sigma_1 \sim N(\beta_1, \sigma_1^2)
\end{equation}\]</span></p>
</section>
<section id="section-38" class="slide level2">
<h2></h2>
<p>But these priors aren’t yet complete – <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span> work <em>together</em> to describe the model for runner <span class="math inline">\(j\)</span>, and thus are <em>correlated</em>. Let <span class="math inline">\(\rho \in [-1,1]\)</span> represent the correlation between <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span>. To reflect this correlation, we represent the <em>joint</em> Normal model of <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span> by</p>
<p><span class="math display">\[\begin{equation}
\left(\begin{array}{c}
\beta_{0j} \\
\beta_{1j} \\
\end{array}\right) \vert
\beta_0, \beta_1, \sigma_0, \sigma_1
\;\; \sim \;\;
N\left(
\left(\begin{array}{c}
\beta_0 \\
\beta_1 \\
\end{array}\right), \;
\Sigma
\right)
\end{equation}\]</span></p>
<p>(continued on the next slide)</p>
</section>
<section id="section-39" class="slide level2">
<h2></h2>
<p>where <span class="math inline">\((\beta_0, \beta_1)\)</span> is the joint mean and <span class="math inline">\(\Sigma\)</span> is the 2x2 <strong>covariance matrix</strong> which encodes the variability and correlation amongst <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\Sigma = \left(\begin{array}{cc}
\sigma_0^2 &amp;  \rho \sigma_0 \sigma_1 \\
\rho \sigma_0 \sigma_1  &amp; \sigma_1^2 \\
\end{array}\right)
\end{equation}\]</span></p>
</section>
<section id="section-40" class="slide level2">
<h2></h2>
<p>On the next slide, plot (a) illustrates the scenario in which there’s a strong <em>negative</em> correlation between <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span> – models that start out lower (with small <span class="math inline">\(\beta_{0j}\)</span>) tend to increase at a more rapid rate (with higher <span class="math inline">\(\beta_{1j}\)</span>). In plot (c) there’s a strong <em>positive</em> correlation between <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span> – models that start out higher (with larger <span class="math inline">\(\beta_{0j}\)</span>) also tend to increase at a more rapid rate (with higher <span class="math inline">\(\beta_{1j}\)</span>). In between these two extremes, plot (b) illustrates the scenario in which there’s no correlation between the group-specific intercepts and slopes.</p>
</section>
<section id="section-41" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-28-1.png" width="960" class="r-stretch"></section>
<section id="section-42" class="slide level2">
<h2></h2>
<p><strong>hierarchical random intercepts and slopes model</strong>:</p>
<p><span class="math display">\[\begin{equation}
\begin{array}{rl}
Y_{ij} | \beta_{0j}, \beta_{1j}, \sigma_y &amp; \sim N(\mu_{ij}, \sigma_y^2) \;\; \text{ where } \; \mu_{ij} = \beta_{0j} + \beta_{1j} X_{ij}   \\
&amp; \\
\left(\begin{array}{c}
\beta_{0j} \\
\beta_{1j} \\
\end{array}\right) \vert
\beta_0, \beta_1, \sigma_0, \sigma_1 &amp; \sim
N\left(
\left(\begin{array}{c}
\beta_0 \\
\beta_1 \\
\end{array}\right), \;
\Sigma
\right) \\
&amp; \\
\beta_{0c} &amp; \sim N(100, 10^2)  \\
\beta_1 &amp; \sim N(2.5, 1^2) \\
\sigma_y &amp; \sim \text{Exp}(0.072)    \\
\Sigma &amp; \sim \text{(decomposition of covariance)}. \\
\end{array}
\end{equation}\]</span></p>
</section>
<section id="section-43" class="slide level2">
<h2></h2>
<p>Equivalently, we can re-express the random intercepts and slopes as random tweaks to the global intercept and slope: <span class="math inline">\(\mu_{ij} = (\beta_0 + b_{0j}) + (\beta_1 + b_{1j}) X_{ij}\)</span> with</p>
<p><span class="math display">\[\left(\begin{array}{c}
b_{0j} \\
b_{1j} \\
\end{array}\right) \vert \; \sigma_0, \sigma_1 \sim
N\left(
\left(\begin{array}{c}
0 \\
0 \\
\end{array}\right), \;
\Sigma
\right)\]</span></p>
</section>
<section id="section-44" class="slide level2">
<h2></h2>
<p><strong>Connecting our hierarchical models</strong></p>
<p>The random intercepts model is a <em>special case</em> of random intercepts and random slopes model. When <span class="math inline">\(\sigma_1 = 0\)</span>, i.e., when the group-specific age coefficients do <em>not</em> differ from group to group, these two models are equivalent.</p>
</section>
<section id="section-45" class="slide level2">
<h2></h2>
<p>We need a <em>joint</em> prior model to express our understanding of how the <em>combined</em> <span class="math inline">\(\sigma_0\)</span>, <span class="math inline">\(\sigma_1\)</span>, and <span class="math inline">\(\rho\)</span> parameters define covariance matrix <span class="math inline">\(\Sigma\)</span>.</p>
<div class="fragment">
<p>The <code>stan_glmer()</code> function allows users to define this prior through a <strong>decomposition of covariance</strong>, or <code>decov()</code>, model.</p>
</div>
<div class="fragment">
<p>Very generally speaking, this model <em>decomposes</em> our prior model for the covariance matrix into prior information about three separate pieces:</p>
</div>
</section>
<section id="section-46" class="slide level2">
<h2></h2>
<ol type="1">
<li class="fragment"><p>the correlation between the group-specific intercepts and slopes, <span class="math inline">\(\rho\)</span>;</p></li>
<li class="fragment"><p>the combined degree to which the intercepts and slopes vary by group, <span class="math inline">\(\sigma_0^2 + \sigma_1^2\)</span>;</p></li>
<li class="fragment"><p>the relative proportion of this variability between groups that’s due to differing intercepts vs differing slopes,</p>
<p><span class="math display">\[\pi_0 = \frac{\sigma_0^2}{\sigma_0^2 + \sigma_1^2} \;\; \text{ vs } \;\; \pi_1 = \frac{\sigma_1^2}{\sigma_0^2 + \sigma_1^2}\]</span></p></li>
</ol>
</section>
<section id="section-47" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-29-1.png" width="960" class="r-stretch"></section>
<section id="section-48" class="slide level2">
<h2></h2>
<p>In general, <span class="math inline">\(\pi_0\)</span> and <span class="math inline">\(\pi_1\)</span> always sum to 1, and thus have a push-and-pull relationship.For example, when <span class="math inline">\(\pi_0 \approx 1\)</span> and <span class="math inline">\(\pi_1 \approx 0\)</span>, the variability in intercepts ( <span class="math inline">\(\sigma_0^2\)</span> ) is large in comparison to the variability in slopes ( <span class="math inline">\(\sigma_1^2\)</span> ).</p>
<div class="fragment">
<p>Thus, the majority of the variability between group-specific models is explained by differences in <em>intercepts</em> (plot a).</p>
</div>
<div class="fragment">
<p>In contrast, when <span class="math inline">\(\pi_0 \approx 0\)</span> and <span class="math inline">\(\pi_1 \approx 1\)</span>, the majority of the variability between group-specific models is explained by differences in <em>slopes</em> (plot c).</p>
</div>
<div class="fragment">
<p>In between these extremes, when <span class="math inline">\(\pi_0\)</span> and <span class="math inline">\(\pi_1\)</span> are both approximately 0.5, roughly half of the variability between groups can be explained by differing intercepts and the other half by differing slopes (plot b).</p>
</div>
</section>
<section id="section-49" class="slide level2">
<h2></h2>
<p>In our analysis, we’ll utilize the weakly informative default setting for the hierarchical random intercepts and slopes model: <code>decov(reg = 1, conc = 1, shape = 1, scale = 1)</code> in <strong>rstanarm</strong> notation.</p>
<p>This makes the following prior assumptions regarding the three pieces above:</p>
<p>1.the correlation <span class="math inline">\(\rho\)</span> is equally likely to be anywhere between -1 and 1; 2.we have weakly informative prior information about the total degree to which the intercepts and slopes vary by runner; and 3.the relative proportion of the variability between runners that’s due to differing intercepts is equally likely to be anywhere between 0 and 1,</p>
</section>
<section id="posterior-simulation-analysis-1" class="slide level2">
<h2>Posterior simulation &amp; analysis</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a>running_model_2 <span class="ot">&lt;-</span> <span class="fu">stan_glmer</span>(</span>
<span id="cb27-2"><a href=""></a>  net <span class="sc">~</span> age <span class="sc">+</span> (age <span class="sc">|</span> runner),</span>
<span id="cb27-3"><a href=""></a>  <span class="at">data =</span> running, <span class="at">family =</span> gaussian,</span>
<span id="cb27-4"><a href=""></a>  <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">100</span>, <span class="dv">10</span>),</span>
<span id="cb27-5"><a href=""></a>  <span class="at">prior =</span> <span class="fu">normal</span>(<span class="fl">2.5</span>, <span class="dv">1</span>), </span>
<span id="cb27-6"><a href=""></a>  <span class="at">prior_aux =</span> <span class="fu">exponential</span>(<span class="dv">1</span>, <span class="at">autoscale =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-7"><a href=""></a>  <span class="at">prior_covariance =</span> <span class="fu">decov</span>(<span class="at">reg =</span> <span class="dv">1</span>, <span class="at">conc =</span> <span class="dv">1</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">scale =</span> <span class="dv">1</span>),</span>
<span id="cb27-8"><a href=""></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">84735</span>, <span class="at">adapt_delta =</span> <span class="fl">0.99999</span></span>
<span id="cb27-9"><a href=""></a>)</span>
<span id="cb27-10"><a href=""></a></span>
<span id="cb27-11"><a href=""></a><span class="co"># Confirm the prior model specifications</span></span>
<span id="cb27-12"><a href=""></a><span class="fu">prior_summary</span>(running_model_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>This simulation will be sloooooooow.</strong></p>
</section>
<section id="section-50" class="slide level2">
<h2></h2>
<h4 id="posterior-analysis-of-the-global-and-group-specific-parameters">Posterior analysis of the global and group-specific parameters</h4>
<p>Remember thinking that the 40 parameters in the random intercepts model was a lot? This new model has 78 parameters: 36 runner-specific intercept parameters <span class="math inline">\(\beta_{0j}\)</span>, 36 runner-specific age coefficients <span class="math inline">\(\beta_{1j}\)</span>, and 6 global parameters ( <span class="math inline">\(\beta_0, \beta_1, \sigma_y, \sigma_0, \sigma_1, \rho\)</span> ). Let’s examine these piece by piece, starting with the global model of the relationship between running time and age,</p>
<p><span class="math display">\[\beta_0 + \beta_1 X\]</span></p>
</section>
<section id="section-51" class="slide level2">
<h2></h2>
<p>The posterior median model is 18.6 + 1.31 age.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="co"># Quick summary of global regression parameters</span></span>
<span id="cb28-2"><a href=""></a><span class="fu">tidy</span>(running_model_2, <span class="at">effects =</span> <span class="st">"fixed"</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.80</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    18.6     11.8       3.32     33.5 
2 age             1.31     0.217     1.04      1.60</code></pre>
</div>
</div>
</section>
<section id="section-52" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="co"># Get MCMC chains for the runner-specific intercepts &amp; slopes</span></span>
<span id="cb30-2"><a href=""></a>runner_chains_2 <span class="ot">&lt;-</span> running_model_2 <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href=""></a>  <span class="fu">spread_draws</span>(<span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, b[term, runner], <span class="st">`</span><span class="at">age</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href=""></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> term, <span class="at">names_glue =</span> <span class="st">"b_{term}"</span>,</span>
<span id="cb30-5"><a href=""></a>              <span class="at">values_from =</span> b) <span class="sc">%&gt;%</span> </span>
<span id="cb30-6"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">runner_intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">b_(Intercept)</span><span class="st">`</span>,</span>
<span id="cb30-7"><a href=""></a>         <span class="at">runner_age =</span> age <span class="sc">+</span> b_age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-53" class="slide level2">
<h2></h2>
<p><code>spread_draws()</code> uses <code>b[term, runner]</code> to grab the chains for all runner-specific parameters. As usual now, these chains correspond to <span class="math inline">\(b_{0j}\)</span> and <span class="math inline">\(b_{1j}\)</span>, the <em>differences</em> between the runner-specific vs global intercepts and age coefficients.</p>
<div class="fragment">
<p><code>pivot_wider()</code> creates separate columns for each of the <span class="math inline">\(b_{0j}\)</span> and <span class="math inline">\(b_{1j}\)</span> chains and names these <code>b_(Intercept)</code> and <code>b_age</code>.</p>
</div>
<div class="fragment">
<p><code>mutate()</code> obtains the runner-specific intercepts <span class="math inline">\(\beta_{0j} = \beta_0 + b_{0j}\)</span>, named <code>runner_intercept</code>, by summing the global <code>(Intercept)</code> and runner-specific adjustments <code>b_(Intercept)</code>. The runner-specific <span class="math inline">\(\beta_{1j}\)</span> coefficients, <code>runner_age</code>, are created similarly.</p>
</div>
</section>
<section id="section-54" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="co"># Posterior medians of runner-specific models</span></span>
<span id="cb31-2"><a href=""></a>runner_summaries_2 <span class="ot">&lt;-</span> runner_chains_2 <span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href=""></a>  <span class="fu">group_by</span>(runner) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">runner_intercept =</span> <span class="fu">median</span>(runner_intercept),</span>
<span id="cb31-5"><a href=""></a>            <span class="at">runner_age =</span> <span class="fu">median</span>(runner_age))</span>
<span id="cb31-6"><a href=""></a></span>
<span id="cb31-7"><a href=""></a><span class="co"># Check it out</span></span>
<span id="cb31-8"><a href=""></a><span class="fu">head</span>(runner_summaries_2, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  runner    runner_intercept runner_age
  &lt;chr&gt;                &lt;dbl&gt;      &lt;dbl&gt;
1 runner:1              18.6       1.06
2 runner:10             18.6       1.75
3 runner:11             18.6       1.32</code></pre>
</div>
</div>
</section>
<section id="section-55" class="slide level2">
<h2></h2>
<p>The posterior median models for all 36 runners.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a><span class="fu">ggplot</span>(running, <span class="fu">aes</span>(<span class="at">y =</span> net, <span class="at">x =</span> age, <span class="at">group =</span> runner)) <span class="sc">+</span> </span>
<span id="cb33-2"><a href=""></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> runner_summaries_2, <span class="at">color =</span> <span class="st">"gray"</span>,</span>
<span id="cb33-3"><a href=""></a>              <span class="fu">aes</span>(<span class="at">intercept =</span> runner_intercept, <span class="at">slope =</span> runner_age)) <span class="sc">+</span> </span>
<span id="cb33-4"><a href=""></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">61</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">135</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-35-1.png" width="960" class="r-stretch"></section>
<section id="section-56" class="slide level2">
<h2></h2>
<p>The slopes do differ, but not as drastically as we expected.</p>
<div class="fragment">
<p>Their posteriors suggest that, on average, runner 10’s running time increases by just 1.06 minute per year, whereas runner 1’s increases by 1.75 minutes per year:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a>runner_summaries_2 <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href=""></a>  <span class="fu">filter</span>(runner <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"runner:1"</span>, <span class="st">"runner:10"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  runner    runner_intercept runner_age
  &lt;chr&gt;                &lt;dbl&gt;      &lt;dbl&gt;
1 runner:1              18.6       1.06
2 runner:10             18.6       1.75</code></pre>
</div>
</div>
</div>
</section>
<section id="section-57" class="slide level2">
<h2></h2>
<p>For runners 1 and 10, the posterior median relationships between running time and age from the hierarchical random intercepts and slopes model (dashed) are contrasted by the observed no pooled models (blue) and the complete pooled model (black).</p>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-38-1.png" width="960" class="r-stretch"></section>
<section id="posterior-analysis-of-within--and-between-group-variability-1" class="slide level2">
<h2>Posterior analysis of within- and between-group variability</h2>
</section>
<section id="section-58" class="slide level2">
<h2></h2>
<p>Stepping back, we should also ask ourselves: <em>Is it worth it</em>? Incorporating the random runner-specific age coefficients introduced 37 parameters into our model of running time by age.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a><span class="fu">tidy</span>(running_model_2, <span class="at">effects =</span> <span class="st">"ran_pars"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  term                       group    estimate
  &lt;chr&gt;                      &lt;chr&gt;       &lt;dbl&gt;
1 sd_(Intercept).runner      runner      1.36 
2 sd_age.runner              runner      0.251
3 cor_(Intercept).age.runner runner     -0.102
4 sd_Observation.Residual    Residual    5.17 </code></pre>
</div>
</div>
</section>
<section id="section-59" class="slide level2">
<h2></h2>
<p>Consider some highlights of this output:</p>
<p>The standard deviation <span class="math inline">\(\sigma_1\)</span> in the age coefficients <span class="math inline">\(\beta_{1j}\)</span> is likely around 0.251 minutes per year. On the scale of a 10-mile race, this indicates very little variability between the runners when it comes to the rate at which running times change with age.</p>
<div class="fragment">
<p>Per the output for <span class="math inline">\(\sigma_y\)</span>, an individual runner’s net times tend to deviate from their own mean model by roughly 5.17 minutes.</p>
</div>
<div class="fragment">
<p>There’s a weak negative correlation of roughly -0.1017 between the runner-specific <span class="math inline">\(\beta_{0j}\)</span> and <span class="math inline">\(\beta_{1j}\)</span> parameters. Thus, it seems that, <em>ever so slightly</em>, runners that start off faster tend to slow down at a faster rate.</p>
</div>
</section>
<section id="model-evaluation-selection" class="slide level2">
<h2>Model evaluation &amp; selection</h2>
<p><code>complete_pooled_model</code> - Complete pooled model</p>
<p><code>running_model_1</code> - A hierarchical random intercepts model</p>
<p><code>running_model_2</code> - A hierarchical random intercepts and slopes model</p>
</section>
<section id="section-60" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-41-1.png" width="960" class="r-stretch"></section>
<section id="section-61" class="slide level2">
<h2></h2>
<p>So which one should we use?</p>
<div class="fragment">
<ol type="1">
<li class="fragment">How <em>fair</em> is each model?</li>
<li class="fragment">How <em>wrong</em> is each model?</li>
<li class="fragment">How <em>accurate</em> are each model’s posterior predictions?</li>
</ol>
</div>
</section>
<section id="question-1" class="slide level2">
<h2>Question 1</h2>
<p>The context and data collection procedure is the same for each model. Since the data has been anonymized and runners are aware that race results will be public, we think this data collection process is fair. Further, though the models produce slightly different conclusions about the relationship between running time and age (e.g., the hierarchical models conclude this relationship is <em>significant</em>), none of these conclusions seem poised to have a negative impact on society or individuals. Thus, our three models are equally <em>fair</em>.</p>
</section>
<section id="question-2" class="slide level2">
<h2>Question 2</h2>
<p><strong>Posterior predictive checks</strong> suggest that the complete pooled model comparatively underestimates the variability in running times – datasets of running time simulated from the complete pooled posterior tend to exhibit a slightly narrower range than the running times we actually observed. Thus, the complete pooled model is <em>more wrong</em> than the hierarchical models.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">pp_check</span>(complete_pooled_model) <span class="sc">+</span> </span>
<span id="cb38-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"net"</span>, <span class="at">title =</span> <span class="st">"complete pooled model"</span>)</span>
<span id="cb38-3"><a href=""></a><span class="fu">pp_check</span>(running_model_1) <span class="sc">+</span> </span>
<span id="cb38-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"net"</span>, <span class="at">title =</span> <span class="st">"running model 1"</span>)</span>
<span id="cb38-5"><a href=""></a><span class="fu">pp_check</span>(running_model_2) <span class="sc">+</span> </span>
<span id="cb38-6"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"net"</span>, <span class="at">title =</span> <span class="st">"running model 2"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-62" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-43-1.png" width="960" class="r-stretch"></section>
<section id="section-63" class="slide level2">
<h2></h2>
<ol type="1">
<li class="fragment">The complete pooled model isn’t powerful enough to detect the significant relationship between running time and age.</li>
<li class="fragment">Not only have we seen <em>visual</em> evidence that some runners tend to be significantly faster or slower than others, the posterior prediction summaries suggest that there’s significant variability between runners ( <span class="math inline">\(\sigma_0\)</span> ).</li>
</ol>
</section>
<section id="section-64" class="slide level2">
<h2></h2>
<p>In choosing between <code>running_model_1</code> and <code>running_model_2</code>, consider question (3): what’s the <em>predictive accuracy</em> of these models?</p>
</section>
<section id="section-65" class="slide level2">
<h2></h2>
<p>How well do these two models predict the running outcomes of the 36 runners that were part of our sample?</p>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a><span class="co"># Calculate prediction summaries</span></span>
<span id="cb39-2"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb39-3"><a href=""></a><span class="fu">prediction_summary</span>(<span class="at">model =</span> running_model_1, <span class="at">data =</span> running)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mae mae_scaled within_50 within_95
1 2.644473  0.4504525 0.6918919  0.972973</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a><span class="fu">prediction_summary</span>(<span class="at">model =</span> running_model_2, <span class="at">data =</span> running)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mae mae_scaled within_50 within_95
1 2.520358  0.4421742 0.7027027  0.972973</code></pre>
</div>
</div>
</div>
</section>
<section id="section-66" class="slide level2">
<h2></h2>
<p>By all metrics, <code>running_model_1</code> and <code>running_model_2</code> produce similarly accurate posterior predictions.</p>
<div class="fragment">
<p>For both models, the <em>observed</em> net running times tend to be 2.64 and 2.52 minutes, or 0.45 and 0.44 standard deviations, from their posterior mean <em>predictions</em>.</p>
</div>
<div class="fragment">
<p>The posterior predictive models also have similar coverage in terms of the percent of observed running times that fall within their 50% and 95% prediction intervals.</p>
</div>
</section>
<section id="section-67" class="slide level2">
<h2></h2>
<p>Thinking beyond our own sample of runners, we could also utilize <code>prediction_summary_cv()</code> to obtain cross-validated metrics of posterior predictive accuracy.</p>
</section>
<section id="section-68" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a><span class="fu">prediction_summary_cv</span>(<span class="at">model =</span> running_model_1, <span class="at">data =</span> running,</span>
<span id="cb43-2"><a href=""></a>                      <span class="at">k =</span> <span class="dv">10</span>, <span class="at">group =</span> <span class="st">"runner"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-69" class="slide level2">
<h2></h2>
<p>For hierarchical models, the <code>prediction_summary_cv()</code> function divides <em>groups</em>, not individual outcomes <span class="math inline">\(Y\)</span>, into distinct folds.</p>
<div class="fragment">
<p>Thus, if we have 10 groups, 10-fold cross-validation will build each training model using data on 9 groups and test it on the 10th group.</p>
</div>
</section>
<section id="section-70" class="slide level2">
<h2></h2>
<p>After reflecting upon our model evaluation, we’re ready to make a final determination: we choose <code>running_model_1</code>.</p>
<div class="fragment">
<p>The complexity introduced by the additional random age coefficients in <code>running_model_2</code> produced little apparent change or benefit. Thus, the additional complexity simply isn’t worth it (at least not to us).</p>
</div>
</section>
<section id="posterior-prediction" class="slide level2">
<h2>Posterior prediction</h2>
<p>Suppose we want to predict the running time that three different runners will achieve when they’re 61 years old: runner 1, runner 10, and Miles.</p>
</section>
<section id="section-71" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a><span class="co"># Plot runner-specific trends for runners 1 &amp; 10</span></span>
<span id="cb44-2"><a href=""></a>running <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href=""></a>  <span class="fu">filter</span>(runner <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"10"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb44-4"><a href=""></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> net)) <span class="sc">+</span> </span>
<span id="cb44-5"><a href=""></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb44-6"><a href=""></a>    <span class="fu">facet_grid</span>(<span class="sc">~</span> runner) <span class="sc">+</span> </span>
<span id="cb44-7"><a href=""></a>    <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">54</span>, <span class="dv">61</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-47-1.png" width="960" class="r-stretch"></section>
<section id="section-72" class="slide level2">
<h2></h2>
<p>In general, let <span class="math inline">\(Y_{new,j}\)</span> denote a <em>new</em> observation on an <em>observed</em> runner <span class="math inline">\(j\)</span>, specifically runner <span class="math inline">\(j\)</span>’s running time at age 61.</p>
<div class="fragment">
<p><span class="math display">\[Y_{\text{new},j}^{(i)} | \beta_{0j}, \beta_1, \sigma_y  \; \sim \; N\left(\mu_{ij}^{(i)}, \left(\sigma_y^{(i)}\right)^2\right) \;\; \text{ where } \; \mu_{ij}^{(i)} = \beta_{0j}^{(i)} + \beta_1^{(i)} \cdot 61\]</span></p>
</div>
<div class="fragment">
<p>The resulting posterior predictive model will reflect two sources of uncertainty in runner <span class="math inline">\(j\)</span>’s race time: the <strong>within-group sampling variability</strong> <span class="math inline">\(\sigma_y\)</span> (we can’t perfectly predict runner <span class="math inline">\(j\)</span>’s time from their mean model); and <strong>posterior variability</strong> in <span class="math inline">\(\beta_{0j}\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma_y\)</span> (the parameters defining runner <span class="math inline">\(j\)</span>’s relationship between running time and age are unknown and random).</p>
</div>
</section>
<section id="section-73" class="slide level2">
<h2></h2>
<p>Since we don’t have any data on the baseline speed for our new runner, Miles, there’s a third source of uncertainty in predicting his race time: <strong>between-group sampling variability</strong> <span class="math inline">\(\sigma_0\)</span> (baseline speeds vary from runner to runner).</p>
</section>
<section id="section-74" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a><span class="co"># Simulate posterior predictive models for the 3 runners</span></span>
<span id="cb45-2"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb45-3"><a href=""></a>predict_next_race <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(</span>
<span id="cb45-4"><a href=""></a>  running_model_1, </span>
<span id="cb45-5"><a href=""></a>  <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">runner =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"Miles"</span>, <span class="st">"10"</span>),</span>
<span id="cb45-6"><a href=""></a>                       <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">61</span>, <span class="dv">61</span>, <span class="dv">61</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="section-75" class="slide level2">
<h2></h2>
<p>The posterior median prediction is just under 100 minutes, similar to what we’d get if we plugged an age of 61 into the <em>global</em> posterior median model for the average runner:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a>B0 <span class="sc">+</span> B1 <span class="sc">*</span> <span class="dv">61</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 98.58057</code></pre>
</div>
</div>
<p>That is, without any information about Miles, our default assumption is that he’s an average runner.</p>
<div class="fragment">
<p>Our <em>uncertainty</em> in this assumption is reflected by the relatively wide posterior predictive model. Naturally, having observed data on runners 1 and 10, we’re more certain about how fast they will be when they’re 61. But Miles is a wild card – he <em>could</em> be really fast or really slow!</p>
</div>
</section>
<section id="section-76" class="slide level2">
<h2></h2>

<img data-src="10a-hlm-pred_files/figure-revealjs/unnamed-chunk-49-1.png" width="960" class="r-stretch"></section>
<section id="details-longitudinal-data" class="slide level2">
<h2>Details: Longitudinal data</h2>
<p>The <code>running</code> data on <code>net</code> times by <code>age</code> is <strong>longitudinal</strong>.</p>
<p>We observe each runner over time, where this time (or aging) is of primary interest. Though our hierarchical models of this relationship account for the correlation in running times within any runner, they make a simplifying assumption about this correlation: it’s the <em>same</em> across all ages. In contrast, you might imagine that observations at one age are more strongly correlated with observations at similar ages. For example, a runner’s net time at age 60 is likely more strongly correlated with their net time at age 59 than at age 50. This is a limitation of our model</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="https://www.stats115.com/img/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://stats115.com">stats115.com</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="10a-hlm-pred_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="10a-hlm-pred_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="10a-hlm-pred_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <!-- From: https://github.com/quarto-dev/quarto-cli/discussions/557 -->
    <script type="text/javascript">
      Reveal.on('ready', event => {
        if (event.indexh === 0) {
          document.querySelector("div.has-logo > img.slide-logo").style.display = "none";
        }
      });
      Reveal.addEventListener('slidechanged', (event) => {
        if (event.indexh === 0) {
          Reveal.configure({ slideNumber: null });
          document.querySelector("div.has-logo > img.slide-logo").style.display = "none";
        }
        if (event.indexh === 1) { 
          Reveal.configure({ slideNumber: 'c' });
          document.querySelector("div.has-logo > img.slide-logo").style.display = null;
        }
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>